name: bbarekas on the net
markdown: rdiscount
permalink: '/blog/:year/:title/'
lsi: false
pygments: true
url: https://barekas.net

title: bbarekas on the net
author: Bill Barekas
email: bbarekas@gmail.com
description: Bill Barekas, Software Engineer, Long-Distance Runner, Proud-to-be Dad
timezone: Europe/Athens